name: ml_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_mlkit_translation: ^0.9.0
  highlight_text: ^1.7.0
  speech_to_text: ^6.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
